name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Verify source and locales
        run: python3 -B scripts/verify.py
